### ISSUE TITLE
okcomputer to replace is_it_working

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/purl#87]
Exemplar:  purl-fetcher

possibly:
- `/status` endpoint for load-balancer needs and nagios errors
- `/status/[some-dependency]` for nagios warnings;  nagios routes them to approp parties
- `/status/all-dependencies` for full dependency documentation (?)

after this
- [x] purl PR merged to master
- [x] deploy
- [x] update Load Balancer (SAR-3250)
- [ ] update nagios 
  - [x] basic checks (~~sul-dlss/puppet#1001~~, ~~sul-dlss/puppet#1002~~, sul-dlss/puppet#1003, ~~sul-dlss/puppet#1018~~)
  - [x] purl-lb (sul-dlss/puppet/pull/1024)
  - [ ] any individual checks need separate nagios handling? (stacks, embed, feedback?) (#76)
- [x] remove is_it_working (#100)
  - [x] deploy
- [ ] update DevOpsDocs (now new nagios, loadbalancer ...) (sul-dlss/DevOpsDocs/pull/60)

**Comment by ndushay** [comment]
I'm gonna call this DONE.
